---
# this file contains the configuration data for the site

TypingFrog:
  version: "0.1"  # version of the typingfrog used to create this site

widgets:
  -
    name: com.typingfrog.rainette.widget.gratipay
    vars:
      username: pcarion
---
